[book]
title = "Wiki Program"
authors = ["Haoyuan Wei"]
src = "src"
language = "en"
multilingual = false
mathjax-support = false

[build]
build-dir = "docs"

[output.html.fold]
enable = true
level = 0